#!/usr/bin/env python
# -*- coding: UTF-8 -*-
__author__ = "Alexandre D'Hondt"
__version__ = "2.0"
__copyright__ = "A. D'Hondt"
__license__   = "agpl-3.0"
__training__ = "ZSIS CTF - Trivia - Shining (4 points)"
__examples__ = ["archive.zip", "archive.zip -d", "archive.zip -d -k 3"]


from tinyscript import *

from decompressor import *


__doc__ = """
This tool allows to recursively decompress an archive, using multiple Linux
 decompression tools. It currently supports the following tools:
- {}
""".format("\n- ".join(sorted(c[0] for c, _ in \
                              RecursiveDecompressor.formats.values())))


if __name__ == '__main__':
    parser.add_argument("archive", help="input archive")
    parser.add_argument("-d", dest="display", action="store_true",
                        help="display last decompressed file in terminal")
    parser.add_argument("-k", "--keep", type=int, metavar="N", default=1,
                        help="keep the last N levels of archives")
    initialize(globals())
    RecursiveDecompressor(args.archive, args.keep, args.display, logger=logger)
